name: My First Workflow

# Workflow ini berjalan setiap kali ada push ke branch main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah untuk checkout repository Anda
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah untuk menginstal Node.js (jika Anda menggunakan Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Langkah untuk menginstal dependensi
      - name: Install dependencies
        run: npm install

      # Langkah untuk menjalankan pengujian
      - name: Run tests
        run: npm test
